### ISSUE TITLE
Blog post: Time series cross-validation using fable

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3temporal#69]
https://robjhyndman.com/hyndsight/tscv-fable/

In general, the {fable} package might be worth a lock when it comes to methods related to time-series processing.

**Comment by pfistfl** [comment]
Agree, but I am a little hesitant because of al the dependencies.
```r
Imports:
    Rcpp (>= 0.11.0),
    rlang (>= 0.4.6),
    stats,
    dplyr (>= 1.0.0),
    tsibble (>= 0.9.0),
    tibble,
    tidyr,
...
```

**Comment by pat-s** [comment]
Uff indeed, quite heavy!
